### ISSUE TITLE
this facebook live not work?

### ISSUE THREAD

**Issue by mchtylmz** [ThatGuySam/facebook-live-embed-php#1]
hi, this facebook live video php, not work. can ı help you?

**Comment by ThatGuySam** [comment]
I can try. Do you have it running a public website anywhere?

**Comment by mchtylmz** [comment]
I downloaded the files and edited the necessary information.
public website http://ylmz.pw/demo/live/
can you give ftp information if you want?

**Comment by ThatGuySam** [comment]
Did you run `composer install`?

**Comment by mchtylmz** [comment]
manually downloaded and edited.
Let me retry with composer.
i will make a return
thank you

**Comment by mchtylmz** [comment]
Does it work without composer?
Is it possible to edit and run without installing composer?

**Comment by ThatGuySam** [comment]
You can install composer on your computer, run `composer install` and then upload the upload files to your server via ftp.

**Comment by ThatGuySam** [comment]
You can install composer through homebrew with `brew install composer`

If you don't have homebrew yet you get from here:
https://brew.sh

**Comment by mchtylmz** [comment]
install composer and this projects composer install.
http://ylmz.pw/demo/live/
facebook page link https://www.facebook.com/evaavm/

**Comment by mchtylmz** [comment]
Graph returned an error: (#10) To use 'Page Public Content Access', your use of this endpoint must be reviewed and approved by Facebook. To submit this 'Page Public Content Access' feature for review please read our documentation on reviewable features: https://developers.facebook.com/docs/apps/review.

**Comment by ThatGuySam** [comment]
You need to get the Facebook App you set up with it to have it's features reviewed. 
Just follow that docs link they gave you.

**Comment by mchtylmz** [comment]
I've edited the facebook application settings but it still doesn't work. Can you share sample application settings?
demo also running facebook application settings?

**Comment by ThatGuySam** [comment]
Go to https://developers.facebook.com.apps/ then click on the app you've set up for this site. 
That should take you to your app's dashboard. 

From there click **App Review** and then **Permissions and Features**
Search or Scroll until you see **Page Public Content Access** and click Request

From there you'll have to go through describing your app and setting up a privacy policy and what not. 
You probably won't get this all done today but you can create a Facebook privacy policy for free here: https://www.freeprivacypolicy.com
