### ISSUE TITLE
Example page does not work my fans page

### ISSUE THREAD

**Issue by mxideas** [ThatGuySam/facebook-live-embed-php#2]
Hello friend, I tried to copy and paste the URL of my fan page but the transmitted videos do not appear

My Fans Page is: https://www.facebook.com/dccontigodeportes

Would the same thing happen when I installed the script on my server?

**Comment by ThatGuySam** [comment]
I can't really say for sure with so little information. If I were to take a shot in the dark I would try checking your Facebook settings for embedding on external websites.
