### ISSUE TITLE
Graph returned an error: (#15) This method cannot be called with a client token or an app secret embedded in the client code

### ISSUE THREAD

**Issue by z3nth10n** [ThatGuySam/facebook-live-embed-php#3]

**Comment by z3nth10n** [comment]
I was not installing it correctly.

**Comment by nfenyi** [comment]
Actually..you did install it correctly. Just ensure this is disabled in the advanced settings of your facebook app:
![image](https://github.com/user-attachments/assets/bce13758-3645-4d40-9583-3b16f59af920)
