### ISSUE TITLE
[QUESTION] How can I use this util with Laravel?

### ISSUE THREAD

**Issue by guillermo7227** [ThatGuySam/facebook-live-embed-php#6]
How can I use this util with Laravel?
Thanks

**Comment by ThatGuySam** [comment]
You would simply install it to a folder that makes sense for you and require it with the following
`require_once __DIR__ . 'path/to/folder/GetFacebookLiveStream.php';`

Here's an article on using non-composer dependendencies in Laravel 
https://likegeeks.com/install-and-use-non-composer-laravel-packages/
