### ISSUE TITLE
Autoload.php missing

### ISSUE THREAD

**Issue by DougRog** [ThatGuySam/facebook-live-embed-php#8]
I'm getting this error when trying to run index.php. Any idea where I can pull the vendor/autoload.php file for the directory?

PHP Warning:  require_once(/home/potfrdjova50/public_html/enn/facebook-live/vendor/autoload.php): failed to open stream: No such file or directory in /home/potfrdjova50/public_html/enn/facebook-live/index.php on line 3

Thanks.

**Comment by ThatGuySam** [comment]
It sounds like you need to run `composer install` to install dependencies. 

Also, I don't think this library works at all anymore.

**Comment by DougRog** [comment]
Thanks, I figured I was missing an obvious step. I just wanted to check it out anyways, especially for a similar project.

**Comment by ThatGuySam** [comment]
Yeah, I want to try to revive it as a javascript version but Facebook's restrictions are super tight right now.
